/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio1;

import javax.swing.JOptionPane;

/**
 *
 * @author walbonis1
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    double v[];
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcantidadV = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdcrear = new javax.swing.JButton();
        cmdPar = new javax.swing.JButton();
        cmdAutomatico = new javax.swing.JButton();
        cmdProductoria = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cmdMayor = new javax.swing.JButton();
        cmdSumatoria = new javax.swing.JButton();
        cmdMOstar = new javax.swing.JButton();
        cmdBorrar3 = new javax.swing.JButton();
        cmdBorrar4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 2, 18)); // NOI18N
        jLabel1.setText("calculacion de vectores ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 2, 14), new java.awt.Color(0, 246, 249))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Datos :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, -1));
        jPanel2.add(txtcantidadV, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 130, 100));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdcrear.setBackground(new java.awt.Color(0, 204, 204));
        cmdcrear.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdcrear.setForeground(new java.awt.Color(102, 102, 102));
        cmdcrear.setText("Crear");
        cmdcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdcrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 220, -1));

        cmdPar.setBackground(new java.awt.Color(0, 204, 204));
        cmdPar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdPar.setForeground(new java.awt.Color(102, 102, 102));
        cmdPar.setText("LLenado manual");
        cmdPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdParActionPerformed(evt);
            }
        });
        jPanel3.add(cmdPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 220, -1));

        cmdAutomatico.setBackground(new java.awt.Color(0, 204, 204));
        cmdAutomatico.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdAutomatico.setForeground(new java.awt.Color(102, 102, 102));
        cmdAutomatico.setText("llenar automatico");
        cmdAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, -1));

        cmdProductoria.setBackground(new java.awt.Color(0, 204, 204));
        cmdProductoria.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdProductoria.setForeground(new java.awt.Color(102, 102, 102));
        cmdProductoria.setText("Productoria");
        cmdProductoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProductoriaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdProductoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 220, -1));

        jButton5.setBackground(new java.awt.Color(153, 0, 153));
        jButton5.setFont(new java.awt.Font("Ravie", 2, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        cmdMayor.setBackground(new java.awt.Color(0, 204, 204));
        cmdMayor.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdMayor.setForeground(new java.awt.Color(102, 102, 102));
        cmdMayor.setText("Mayor elemento");
        cmdMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 220, -1));

        cmdSumatoria.setBackground(new java.awt.Color(0, 204, 204));
        cmdSumatoria.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdSumatoria.setForeground(new java.awt.Color(102, 102, 102));
        cmdSumatoria.setText("Sumatoria");
        cmdSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumatoriaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSumatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 220, -1));

        cmdMOstar.setBackground(new java.awt.Color(0, 204, 204));
        cmdMOstar.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdMOstar.setForeground(new java.awt.Color(102, 102, 102));
        cmdMOstar.setText("Mostart");
        cmdMOstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMOstarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMOstar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 220, 20));

        cmdBorrar3.setBackground(new java.awt.Color(0, 204, 204));
        cmdBorrar3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdBorrar3.setForeground(new java.awt.Color(102, 102, 102));
        cmdBorrar3.setText("Menor elemento");
        cmdBorrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrar3ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, -1));

        cmdBorrar4.setBackground(new java.awt.Color(0, 204, 204));
        cmdBorrar4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cmdBorrar4.setForeground(new java.awt.Color(102, 102, 102));
        cmdBorrar4.setText("Borrar");
        cmdBorrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrar4ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 320, 290));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("resultado"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(5, 246, 166));
        txtResultado.setColumns(20);
        txtResultado.setForeground(new java.awt.Color(0, 153, 153));
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 120));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 280, 180));

        jButton6.setBackground(new java.awt.Color(244, 0, 8));
        jButton6.setFont(new java.awt.Font("Ravie", 2, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcrearActionPerformed
        double numeroma=0;
        
        if (txtcantidadV.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la cantdad a calcular", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
        } else if (Integer.parseInt(txtcantidadV.getText().trim())==0) {
            JOptionPane.showMessageDialog(this, "la cantidad de elemento no puede ser cero", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
            txtcantidadV.selectAll();

        }else{
        for (int i = 0; i < v.length; i++) {
            if (v[i]>numeroma){
                numeroma = v[i];
            }
            
        }
        txtResultado.append("El numero mayor es: "+numeroma);
            
        }

    }//GEN-LAST:event_cmdcrearActionPerformed

    private void cmdParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdParActionPerformed
         double n,num;
        if (txtcantidadV.getText().trim().isEmpty ()){          
            JOptionPane.showMessageDialog(this, "Digite la cantidad a calcular", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
        }else{
      num = Double.parseDouble (JOptionPane.showInputDialog(this, "Digite el numero hasta donde quiere el llenado automatico "));
           while (num<v.length){
            JOptionPane.showMessageDialog(this, "Digite un numero mayor a : "+v.length);
            num = Double.parseDouble (JOptionPane.showInputDialog(this, "Digite el numero hasta donde quiere el llenado automatico "));
           }
        for (int i = 0; i < v.length; i++) {
             
           n = (int) (Math.random()*num + 1);
           v[i]=n;
        }
       JOptionPane.showMessageDialog(this,"Vector llenado correctamente");
        }
    }//GEN-LAST:event_cmdParActionPerformed

    private void cmdAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticoActionPerformed
        double numero;
        for (int i = 0; i < v.length; i++) {
            numero= (int)(Math.random()*50 + 1);
            v[i]=numero;

        }
        JOptionPane.showMessageDialog(this, "vector llenado correctamente");
    }//GEN-LAST:event_cmdAutomaticoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cmdProductoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProductoriaActionPerformed
 double acum=1;
      String res;
      if (txtcantidadV.getText().trim().isEmpty ()){          
            JOptionPane.showMessageDialog(this, "Digite la cantidad", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
      }else{
        for (int i = 0; i < v.length; i++) {
            acum=v[i]*acum;
            
        }
        res=String.valueOf(acum);
      txtResultado.setText("La Productoria es: "); txtResultado.append(res);
      }
    }//GEN-LAST:event_cmdProductoriaActionPerformed

    private void cmdMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorActionPerformed
      double mayor = 0;
       if (txtcantidadV.getText().trim().isEmpty ()){          
            JOptionPane.showMessageDialog(this, "Digite la cantidad", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
       }else{
        for (int i = 0; i < v.length; i++) {
            if (v[i]>mayor){
                mayor = v[i];
            }
            
        }
        txtResultado.append("El numero mayor es: "+mayor);
       }
    }//GEN-LAST:event_cmdMayorActionPerformed

    private void cmdSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumatoriaActionPerformed
   double acum=0;
      String res;
      if (txtcantidadV.getText().trim().isEmpty ()){          
            JOptionPane.showMessageDialog(this, "Digite la cantidad", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
      }else{
        for (int i = 0; i < v.length; i++) {
            acum=v[i]+acum;
        }
        res=String.valueOf(acum);
      txtResultado.setText("La sumatoria es: "); txtResultado.append(res);
      }
    }//GEN-LAST:event_cmdSumatoriaActionPerformed

    private void cmdMOstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMOstarActionPerformed
     if (txtcantidadV.getText().trim().isEmpty ()){          
            JOptionPane.showMessageDialog(this, "Digite la cantidad", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
       
    }else{

        for (int i = 0; i < v.length; i++) {
            txtResultado.append (v[i]+"\n");
      }
    }
    }//GEN-LAST:event_cmdMOstarActionPerformed

    private void cmdBorrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrar3ActionPerformed
        double menor = 99999999;
        if (txtcantidadV.getText().trim().isEmpty ()){          
            JOptionPane.showMessageDialog(this, "Digite la longitud", "Error", JOptionPane.ERROR_MESSAGE);
            txtcantidadV.requestFocusInWindow();
        }else{
        for (int i = 0; i < v.length; i++) {
            if (v[i]<menor){
                menor = v[i];
            }
            
        }
        txtResultado.append("El numero menor es: "+menor);
        }
    }//GEN-LAST:event_cmdBorrar3ActionPerformed

    private void cmdBorrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrar4ActionPerformed
         txtcantidadV.setText("");
        txtResultado.setText("");
        txtcantidadV.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAutomatico;
    private javax.swing.JButton cmdBorrar3;
    private javax.swing.JButton cmdBorrar4;
    private javax.swing.JButton cmdMOstar;
    private javax.swing.JButton cmdMayor;
    private javax.swing.JButton cmdPar;
    private javax.swing.JButton cmdProductoria;
    private javax.swing.JButton cmdSumatoria;
    private javax.swing.JButton cmdcrear;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextField txtcantidadV;
    // End of variables declaration//GEN-END:variables
}
